### ISSUE TITLE
Error item.js (line 59 cleanString(seller.html().trim()))

### ISSUE THREAD

**Issue by pier7529** [tdurieux/leboncoin-api#19]
With leboncoin-api@0.0.15 , since few days, I got this error 

execution --> 2018-2-22 22:00:10 GMT+1
/volume1/dev/projets/node_modules/leboncoin-api/lib/item.js:59
    return cleanString(seller.html().trim());
                                    ^
TypeError: Cannot read property 'trim' of null
    at parseSeller (/volume1/dev/projets/node_modules/leboncoin-api/lib/item.js:59:37)
    at Request._callback (/volume1/dev/projets/node_modules/leboncoin-api/lib/item.js:159:27)
    at Request.self.callback (/volume1/dev/projets/node_modules/request/request.js:186:22)
    ...

**Comment by tdurieux** [comment]
Thanks for the report, leboncoin probably changes the structure of the page.
I will look at it.

**Comment by tdurieux** [comment]
fixed in 0.0.16 Thanks

**Comment by pier7529** [comment]
Thanks for your answer but unfortunately I still have the same error.
After update to 0.0.16, I deleted all node_modules, and retry.

I put also 3 of my queries (without query content):

{"searchExtras":{"mrs":100,"mre":500},"query":"<myRequest>","category":"informatique","region":"ile_de_france","page":1}

{"searchExtras":{"mrs":100,"mre":500},"query":"<myRequest>","category":"image_son","region":"france","page":1}

{"searchExtras":{"mrs":100,"mre":500},"query":"<myRequest>","category":"telephonie","region":"ile_de_france","page":1}

Sortie standard/erreur :
node: /lib/libstdc++.so.6: no version information available (required by node)
node: /lib/libstdc++.so.6: no version information available (required by node)
node: /lib/libstdc++.so.6: no version information available (required by node)
node: /lib/libstdc++.so.6: no version information available (required by node)
node: /lib/libstdc++.so.6: no version information available (required by node)
node: /lib/libstdc++.so.6: no version information available (required by node)
execution --> 2018-2-26 13:40:10 GMT+1
/volume1/dev/projets/node_modules/leboncoin-api/lib/item.js:59
    return cleanString(seller.html().trim());
                                    ^

TypeError: Cannot read property 'trim' of null
    at parseSeller (/volume1/dev/projets/node_modules/leboncoin-api/lib/item.js:59:37)
    at Request._callback (/volume1/dev/projets/node_modules/leboncoin-api/lib/item.js:159:27)
    at Request.self.callback (/volume1/dev/projets/node_modules/request/request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/volume1/dev/projets/node_modules/request/request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Gunzip.<anonymous> (/volume1/dev/projets/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at Gunzip.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Hope that will help you,
Let me know,

**Comment by tdurieux** [comment]
That is strange because I removed the method parseSeller. I will check

**Comment by tdurieux** [comment]
Are you sure that you correctly updated the version to 0.0.16.
Because I just did an install and the line `return cleanString(seller.html().trim());` does not exist anymore.

**Comment by pier7529** [comment]
I will check later my package.json. Thanks.

**Comment by pier7529** [comment]
You are right. My package.json was sticked to "leboncoin-api": "0.0.15", After update, everything is working.
Thanks a lot 👍

**Comment by tdurieux** [comment]
No problem :)
